# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



trigger: 
  - dev

pool:
  name: 'ERP_DEV'
  
jobs:
  - job: DotnetBuild
    steps: 
    - script: |
        export PATH=$PATH:/opt/dotnet3/
        cd aspnet-core/src/Erpinfo.Migrator
        dotnet3 publish -c Release
      displayName: 'Dotnet Release Migrator'

    - script: |
        cd aspnet-core/src/Erpinfo.Migrator/bin/Release/netcoreapp3.1/publish/
        zip -r backend_migrator.zip *
      displayName: 'Compress Publish Migrator'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'aspnet-core/src/Erpinfo.Migrator/bin/Release/netcoreapp3.1/publish/backend_migrator.zip'
        ArtifactName: 'dev-dotnet-migrator-ims'
        publishLocation: 'Container'
      displayName: 'Publish Artifacts Migrator'

    - script: |
        export PATH=$PATH:/opt/dotnet3/
        cd aspnet-core
        dotnet3 publish -c Release
      displayName: 'Dotnet Release Host'

    - script: |
        cd aspnet-core/src/Erpinfo.Web.Host/bin/Release/netcoreapp3.1/publish/
        zip -r backend_publish.zip *
      displayName: 'Compress Release Host'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'aspnet-core/src/Erpinfo.Web.Host/bin/Release/netcoreapp3.1/publish/backend_publish.zip'
        ArtifactName: 'dev-dotnet-host-ims'
        publishLocation: 'Container'
      displayName: 'Publish Artifacts Host'

  - job: VuejsBuild
    steps:
      - script: |
          cd vue 
          export NVM_DIR="$HOME/.nvm" && . "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
          nvm use 14.17.0
          node -v
          rm -rf node_modules/
          echo "===Install Package==="
          npm i
          echo "===Build node==="
          npm run build --prod
        displayName: 'Build Frontend'
      
      - script: |
          cd vue/dist
          zip -r frontend_publish.zip *
        displayName: 'Compress Build FE'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'vue/dist/frontend_publish.zip'
          ArtifactName: 'dev-fe-ims'
          publishLocation: 'Container'
        displayName: 'Publish Artifacts Frontend'

